[package]
name = "moff"
version = "0.1.3"
authors = ["Rrogntudju"]
edition = "2018"
build = "build/build.rs"

[dependencies]
windows = "0.11"

[build-dependencies]
winres = "0.1"
windows = "0.11"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
