[package]
name = "moff"
version = "0.1.1"
authors = ["Rrogntudju"]
edition = "2018"
build = "build/build.rs"

[dependencies]
windows = "0.9"

[build-dependencies]
winres = "0.1"
windows = "0.9"

[profile.release]
lto = true 
