[package]
name = "moff"
version = "0.1.3"
authors = ["Rrogntudju"]
edition = "2021"

[dependencies]
windows = { version = "0.48", features = ["Win32_Devices_Display", "Win32_Foundation", "Win32_Graphics_Gdi"] }

[profile.release]
opt-level = 3
lto = "thin"
